name: MeD-An-Cr Oto-Analiz Motoru

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Depoyu Klonla
      uses: actions/checkout@v4

    - name: Python Kurulumu
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Bağımlılıkları Yükle
      run: |
        pip install requests

    - name: Analiz Motorunu Çalıştır ve Veri Üret
      env:
        CR_API_KEY: ${{ secrets.CR_API_KEY }}
      run: |
        python backend/analyzer.py

    - name: Verileri Artifact Olarak Yükle
      uses: actions/upload-artifact@v4
      with:
        name: med-clash-analiz-verileri
        path: frontend/data/
        retention-days: 7 # Verilerin kaç gün saklanacağını belirler (Maksimum 90)
        
